// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentGuideState } from "./AgentGuideState";
import type { AgentId } from "./AgentId";

export type AgentGuideStatusPayload = { agent: AgentId, state: AgentGuideState, path: string, detail: string | null, };
