// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptionProviderPreference } from "./TranscriptionProviderPreference";

export type AppSettings = { transcriptsDir: string | null, saveRawAudio: boolean, markdownCopy: boolean, transcriptionProvider: TranscriptionProviderPreference, };
