// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { transcriptsDir: string | null, transcriptsFolderUnavailable: boolean, saveRawAudio: boolean, markdownCopy: boolean, meetingRemindersEnabled: boolean, meetingCalendarIds: Array<string>, meetingReminderMinutes: number, meetingEndReminders: boolean, };
