// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a thread came from, when it was started from a calendar event. Carried
 * so the thread can be found by who was in it and when, without reading the
 * transcript. `None` for manually started threads.
 */
export type CalendarProvenance = { 
/**
 * EventKit occurrence key: event identifier plus that occurrence's start.
 */
eventId: string, calendarId: string, 
/**
 * Invitees other than the current user, in invite order.
 */
attendees: Array<string>, startAtMs: number, endAtMs: number, };
