// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LegacyImportPreview = { activeRecordings: number, archivedRecordings: number, duplicates: number, conflicts: number, bytesToCopy: number, sourcePath: string, };
