// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveTranscriptStatusPayload = { threadId: string, active: boolean, message: string, chunkMs: number, overlapMs: number, };
