// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeetingCalendarPayload = { id: string, title: string, 
/**
 * Owning account, e.g. "iCloud" or a Google address. Calendars from
 * different accounts frequently share a title, so this disambiguates them.
 */
account: string, 
/**
 * `#rrggbb`, matching the calendar's colour in macOS Calendar.
 */
color: string, };
