// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeetingCalendarPayload } from "./MeetingCalendarPayload";

export type MeetingAccessPayload = { calendarAuthorization: string, notificationAuthorization: string, calendars: Array<MeetingCalendarPayload>, };
