// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadDetail } from "./ThreadDetail";
import type { TranscriptionStatusPayload } from "./TranscriptionStatusPayload";

export type RecordingPayload = { thread: ThreadDetail, transcription: TranscriptionStatusPayload, };
