// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageUsagePayload = { totalBytes: number, rawAudioBytes: number, reclaimableBytes: number, threadCount: number, };
