// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadStatus } from "./ThreadStatus";

export type ThreadSummary = { id: string, title: string, createdAtMs: number, updatedAtMs: number, status: ThreadStatus, segmentCount: number, path: string, };
