// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSummary } from "./ThreadSummary";
import type { TranscriptSegment } from "./TranscriptSegment";

export type ThreadDetail = { summary: ThreadSummary, segments: Array<TranscriptSegment>, speakerLabels: { [key in string]: string }, transcriptMarkdownPath: string, };
