// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptionModelDownloadState } from "./TranscriptionModelDownloadState";

export type TranscriptionModelStatus = { name: string, filename: string, path: string, installed: boolean, selected: boolean, downloadable: boolean, downloadState: TranscriptionModelDownloadState, progressBytes: number, totalBytes: number, displaySize: string, canDownload: boolean, canCancel: boolean, errorMessage: string | null, };
