// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisperModelStatus } from "./WhisperModelStatus";

export type TranscriptionStatusPayload = { ready: boolean, engineExists: boolean, modelExists: boolean, enginePath: string, modelPath: string, modelName: string, availableModels: Array<WhisperModelStatus>, message: string, };
