// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptionModelStatus } from "./TranscriptionModelStatus";
import type { TranscriptionProvider } from "./TranscriptionProvider";

export type TranscriptionStatusPayload = { ready: boolean, engineExists: boolean, modelExists: boolean, enginePath: string, modelPath: string, modelName: string, provider: TranscriptionProvider, availableModels: Array<TranscriptionModelStatus>, message: string, };
