// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WhisperModelStatus = { name: string, filename: string, path: string, installed: boolean, selected: boolean, };
